//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoogleFitApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public int GameID { get; set; }
        public string GameTitle { get; set; }
        public Nullable<System.DateTime> GameStartDate { get; set; }
        public Nullable<System.DateTime> GameEndDate { get; set; }
        public string GameType { get; set; }
        public Nullable<int> MaximumNumberOfParticipant { get; set; }
        public Nullable<System.DateTime> RegistrationDeadline { get; set; }
        public Nullable<decimal> Prize { get; set; }
        public Nullable<decimal> RegistrationFee { get; set; }
        public string PosterImage { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<int> CreatorPlayerID { get; set; }
    }
}
