//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoogleFitApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerJoinedGame
    {
        public int PlayerJoinedID { get; set; }
        public int Player_Id { get; set; }
        public int Game_Id { get; set; }
        public Nullable<System.DateTime> JoinedDateTime { get; set; }
        public Nullable<int> Score { get; set; }
        public string GoogleFitDateJson { get; set; }
        public string GoogleFitValue { get; set; }
    }
}
